name: Deploy to GitHub Pages
on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install deps
        run: npm ci || npm i
      - name: Build (auto-detect Vite)
        shell: bash
        run: |
          REPO_NAME="${GITHUB_REPOSITORY##*/}"
          if grep -qi '"vite"' package.json; then
            npx vite build --base "/$REPO_NAME/"
            echo "out_dir=dist" >> $GITHUB_ENV
          else
            npm run build
            if [ -d dist ]; then echo "out_dir=dist" >> $GITHUB_ENV; else echo "out_dir=build" >> $GITHUB_ENV; fi
          fi
      - name: Configure Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.out_dir }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
